AllCops:
  Includes:
    - Rakefile
    - config.ru
    - Gemfile
    - Capfile
    - db/seeds.rb
    - lib/**/*.rake
    - lib/**/*.cap
  Excludes:
    - spec/spec_helper.rb
    - db/**
    - config/application.rb
    - bin/**

Documentation:
  Enabled: false

MethodLength:
  Max: 5

ClassLength:
  Max: 100
