AllCops:
  Includes:
    - Rakefile
    - config.ru
    - Gemfile
  Excludes:
    - spec/spec_helper.rb
    - db/**
    - config/application.rb

Documentation:
  Enabled: false

MethodLength:
  Max: 5

ClassLength:
  Max: 100
