---
development:
  adapter: mysql2
  database: digiquatics_development
  encoding: utf8
  password: ~
  pool: 5
  socket: /tmp/mysql.sock
  username: root
production:
  adapter: mysql2
  database: rails
  encoding: utf8
  host: localhost
  password: clZVEKypAA
  pool: 5
  reconnect: false
  socket: /var/run/mysqld/mysqld.sock
  username: rails
test:
  adapter: mysql2
  database: digiquatics_test
  encoding: utf8
  password: ~
  pool: 5
  socket: /tmp/mysql.sock
  username: root
