development:
  adapter: mysql2
  encoding: utf8
  database: digiquatics_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: digiquatics_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: rails
  reconnect: false
  host: localhost
  pool: 5
  username: rails
  password: clZVEKypAA
  socket: /var/run/mysqld/mysqld.sock
