Account.create(name: 'City of Lakewood',
                   time_zone: 'Mountain Time (US & Canada)')

User.create!(first_name:            'First',
                 nickname:              'Dubs',
                 last_name:             'Last',
                 phone_number:          '303-123-4567',
                 email:                 'example@affektive.com',
                 password:              'foobar22',
                 password_confirmation: 'foobar22',
                 date_of_birth:         '1992-09-15',
                 sex:                   'F',
                 address1:              '14277 E Warren Dr.',
                 address2:              'Unit B',
                 city:                  'Lakewood',
                 state:                 'CO',
                 zipcode:               '80228',
                 shirt_size:            'M',
                 suit_size:             'M',
                 femalesuit:            '30',
                 emergency_first:       'Lydia',
                 emergency_last:        'Campbell',
                 emergency_phone:       '303-222-1313',
                 location_id:           1,
                 position_id:           2,
                 employee_id:           1313,
                 grouping:              'West',
                 date_of_hire:          '2008-07-01',
                 payrate:               '9.50',
                 admin:                 true,
                 active:                true,
                 account_id:            1)
